import { NutriGrade } from './types';
import { GoalType } from './bmr';

export interface Recipe {
  id: string;
  name: string;
  cuisine: string;
  prepTime: number;
  cookTime: number;
  servings: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  difficulty: 'easy' | 'medium' | 'hard';
  tags: string[];
  ingredients: string[];
  steps: string[];
  imageEmoji: string;
  grade: NutriGrade;
  tip?: string;
}

export const RECIPES: Recipe[] = [
  {
    id: 'ytf-clear-soup',
    name: 'Yong Tau Foo (Clear Soup)',
    cuisine: 'Singaporean',
    prepTime: 5, cookTime: 10, servings: 1,
    calories: 280, protein: 22, carbs: 30, fat: 6, fiber: 4,
    difficulty: 'easy',
    tags: ['low-fat', 'high-protein', 'soup'],
    imageEmoji: '🍲', grade: 'A',
    ingredients: [
      '6–8 pieces yong tau foo (tofu, fish paste stuffed veg)',
      '1 bowl clear fish or chicken broth',
      'Bee hoon or mee pok (small portion)',
      'Sliced chili & soy sauce to taste',
      'Spring onion for garnish',
    ],
    steps: [
      'Heat fish broth to a gentle simmer.',
      'Add yong tau foo pieces; cook 5–8 minutes.',
      'Cook noodles separately per package; drain.',
      'Combine in bowl, pour broth over, add yong tau foo.',
      'Garnish with spring onion; serve chili on side.',
    ],
    tip: 'Choose tofu and vegetable pieces over fried ones to save ~60 kcal.',
  },
  {
    id: 'steamed-ginger-fish',
    name: 'Steamed Ginger Soy Fish',
    cuisine: 'Chinese',
    prepTime: 10, cookTime: 12, servings: 2,
    calories: 195, protein: 30, carbs: 4, fat: 6, fiber: 0,
    difficulty: 'easy',
    tags: ['high-protein', 'low-carb', 'steamed'],
    imageEmoji: '🐟', grade: 'A',
    ingredients: [
      '400g sea bass or grouper, cleaned',
      '3cm fresh ginger, julienned',
      '2 tbsp light soy sauce',
      '1 tbsp sesame oil',
      '2 stalks spring onion, shredded',
      '1 red chili, sliced (optional)',
    ],
    steps: [
      'Score fish 3 times on each side; stuff ginger inside cavity.',
      'Steam on high heat 10–12 minutes until flesh flakes.',
      'Discard steaming liquid; pour soy sauce over fish.',
      'Heat sesame oil until just smoking; drizzle over fish.',
      'Top with ginger, spring onion, and chili.',
    ],
    tip: 'Sea bass is leaner than pomfret but equally delicious when fresh.',
  },
  {
    id: 'chicken-congee',
    name: 'Chicken Congee',
    cuisine: 'Chinese',
    prepTime: 10, cookTime: 40, servings: 2,
    calories: 285, protein: 25, carbs: 38, fat: 3, fiber: 1,
    difficulty: 'easy',
    tags: ['comforting', 'low-fat', 'high-protein'],
    imageEmoji: '🥣', grade: 'B',
    ingredients: [
      '150g jasmine rice, rinsed and soaked 20 min',
      '200g chicken breast',
      '1.2L low-sodium chicken broth',
      '2cm ginger, sliced',
      'White pepper, ½ tsp sesame oil',
      'Spring onion, fried shallots to garnish',
    ],
    steps: [
      'Bring broth with ginger to boil; add drained rice.',
      'Simmer on low 30–35 minutes, stirring occasionally until creamy.',
      'Poach chicken breast in simmering water 15 minutes; shred.',
      'Serve congee topped with chicken, spring onion, and pepper.',
    ],
    tip: 'Brown rice adds more fiber but needs 15 extra minutes of cooking.',
  },
  {
    id: 'pho-clear',
    name: 'Pho Bo (Beef Noodle Soup)',
    cuisine: 'Vietnamese',
    prepTime: 10, cookTime: 15, servings: 1,
    calories: 380, protein: 28, carbs: 45, fat: 8, fiber: 2,
    difficulty: 'easy',
    tags: ['clear-soup', 'high-protein'],
    imageEmoji: '🍜', grade: 'A',
    ingredients: [
      '80g flat rice noodles',
      '120g lean beef, thinly sliced',
      '600ml clear pho broth',
      'Bean sprouts, Thai basil, lime',
      'Spring onion and chili',
    ],
    steps: [
      'Soak rice noodles per package; drain.',
      'Bring broth to a rolling boil.',
      'Place noodles in bowl; arrange raw beef on top.',
      'Pour boiling broth over — this cooks the beef.',
      'Add sprouts, basil, lime squeeze; sauces on side.',
    ],
    tip: 'Skip hoisin sauce to save ~30 kcal and cut sugar significantly.',
  },
  {
    id: 'bibimbap',
    name: 'Bibimbap (Mixed Rice Bowl)',
    cuisine: 'Korean',
    prepTime: 20, cookTime: 15, servings: 1,
    calories: 490, protein: 22, carbs: 68, fat: 12, fiber: 5,
    difficulty: 'medium',
    tags: ['balanced', 'colorful', 'filling'],
    imageEmoji: '🍱', grade: 'B',
    ingredients: [
      '150g cooked short-grain rice',
      '80g lean beef mince',
      '2 cups mixed veg (spinach, carrot, zucchini, bean sprouts)',
      '1 egg, fried sunny-side up',
      '1 tsp sesame oil',
      '1 tbsp gochujang (adjust)',
    ],
    steps: [
      'Sauté each vegetable separately with salt and sesame oil.',
      'Cook beef with soy sauce, garlic, sesame oil.',
      'Arrange rice in bowl; place veg and beef in sections.',
      'Top with fried egg and gochujang.',
      'Mix everything together before eating.',
    ],
    tip: 'Half the gochujang cuts sodium by 40% without sacrificing much flavor.',
  },
  {
    id: 'miso-soup',
    name: 'Miso Soup with Tofu & Wakame',
    cuisine: 'Japanese',
    prepTime: 5, cookTime: 5, servings: 2,
    calories: 80, protein: 7, carbs: 6, fat: 3, fiber: 2,
    difficulty: 'easy',
    tags: ['low-calorie', 'quick', 'gut-health'],
    imageEmoji: '🍵', grade: 'A',
    ingredients: [
      '600ml dashi or kombu broth',
      '2 tbsp white miso paste',
      '150g soft tofu, cubed',
      '2 tbsp dried wakame seaweed, rehydrated',
      '2 spring onions, thinly sliced',
    ],
    steps: [
      'Heat dashi to just below boiling — do not boil.',
      'Dissolve miso in a ladleful of broth; stir back in.',
      'Add tofu and wakame; warm through 1 minute.',
      'Serve immediately topped with spring onion.',
    ],
    tip: 'Never boil miso — heat destroys the beneficial probiotics.',
  },
  {
    id: 'tom-yum-clear',
    name: 'Tom Yum Goong (Clear)',
    cuisine: 'Thai',
    prepTime: 10, cookTime: 15, servings: 2,
    calories: 165, protein: 18, carbs: 10, fat: 4, fiber: 1,
    difficulty: 'easy',
    tags: ['low-calorie', 'spicy', 'immune-boost'],
    imageEmoji: '🍤', grade: 'A',
    ingredients: [
      '300g prawns, shelled and deveined',
      '600ml chicken broth',
      '3 stalks lemongrass, bruised',
      '4 kaffir lime leaves',
      '3 slices galangal',
      '3 tbsp fish sauce, 2 tbsp lime juice',
      '200g mushrooms, 2 Thai chilies',
    ],
    steps: [
      'Simmer broth with lemongrass, lime leaves, galangal 5 minutes.',
      'Add mushrooms; cook 3 minutes.',
      'Add prawns; cook until pink, ~2 minutes.',
      'Season with fish sauce and lime juice.',
      'Add chilies; garnish with coriander.',
    ],
    tip: 'Order "nam sai" (clear) not "nam khon" (coconut cream) — saves ~200 kcal.',
  },
  {
    id: 'thunder-tea-rice',
    name: 'Thunder Tea Rice (Lei Cha)',
    cuisine: 'Hakka',
    prepTime: 10, cookTime: 15, servings: 1,
    calories: 420, protein: 18, carbs: 55, fat: 14, fiber: 8,
    difficulty: 'medium',
    tags: ['high-fiber', 'plant-based', 'antioxidant'],
    imageEmoji: '🌿', grade: 'A',
    ingredients: [
      '150g brown rice, cooked',
      '1 cup stir-fried pumpkin leaves or cabbage',
      '1 cup long beans, blanched',
      '50g firm tofu, pan-fried',
      '30g salted radish (rinsed)',
      '1 bowl blended green tea broth',
    ],
    steps: [
      'Arrange cooked rice in a deep bowl.',
      'Place all prepared toppings around rice.',
      'Blend green tea, sesame seeds, peanuts, mint with water for broth.',
      'Pour hot tea broth over rice and toppings.',
      'Stir and eat immediately.',
    ],
    tip: 'Ask for less oil when ordering out — the vegetables are often over-oiled.',
  },
  {
    id: 'edamame',
    name: 'Steamed Edamame',
    cuisine: 'Japanese',
    prepTime: 2, cookTime: 5, servings: 2,
    calories: 120, protein: 11, carbs: 9, fat: 5, fiber: 4,
    difficulty: 'easy',
    tags: ['snack', 'high-protein', 'plant-based'],
    imageEmoji: '🫘', grade: 'A',
    ingredients: ['200g frozen edamame in pods', '1 tsp coarse sea salt'],
    steps: [
      'Steam edamame 4–5 minutes, or microwave with 2 tbsp water covered for 3 minutes.',
      'Toss immediately with sea salt.',
      'Serve in pods — pop beans out to eat.',
    ],
    tip: 'One serving has as much protein as a whole egg. Great pre-meal snack to prevent overeating.',
  },
  {
    id: 'spinach-garlic',
    name: 'Stir-Fried Spinach with Garlic',
    cuisine: 'Chinese',
    prepTime: 3, cookTime: 5, servings: 2,
    calories: 95, protein: 5, carbs: 6, fat: 6, fiber: 3,
    difficulty: 'easy',
    tags: ['quick', 'veg', 'iron-rich'],
    imageEmoji: '🥬', grade: 'A',
    ingredients: [
      '300g baby spinach or kangkong',
      '4 cloves garlic, minced',
      '1 tbsp light soy sauce',
      '1 tbsp cooking oil',
    ],
    steps: [
      'Heat oil in wok on high until smoking.',
      'Add garlic; fry 20 seconds until fragrant.',
      'Add spinach all at once; toss 1–2 minutes until wilted.',
      'Season with soy sauce; serve immediately.',
    ],
    tip: 'High heat and speed are key — overcooked greens lose nutrition and texture.',
  },
  {
    id: 'salmon-teriyaki',
    name: 'Salmon Teriyaki',
    cuisine: 'Japanese',
    prepTime: 5, cookTime: 12, servings: 1,
    calories: 380, protein: 34, carbs: 15, fat: 18, fiber: 0,
    difficulty: 'easy',
    tags: ['omega-3', 'high-protein', 'heart-healthy'],
    imageEmoji: '🐠', grade: 'B',
    ingredients: [
      '150g salmon fillet',
      '2 tbsp soy sauce, 1 tbsp mirin',
      '1 tsp honey or maple syrup',
      '1 tsp sesame seeds',
    ],
    steps: [
      'Mix soy, mirin, honey for teriyaki sauce.',
      'Marinate salmon 10 minutes.',
      'Pan-fry skin-side down on medium-high 4 minutes.',
      'Flip; brush with sauce; cook 3–4 more minutes.',
      'Sprinkle sesame seeds; serve with steamed veg.',
    ],
    tip: 'Aim for 2 servings of fatty fish per week — it\'s one of the best sources of anti-inflammatory omega-3.',
  },
  {
    id: 'tofu-stir-fry',
    name: 'Crispy Tofu & Mixed Veg Stir-fry',
    cuisine: 'Chinese',
    prepTime: 10, cookTime: 10, servings: 2,
    calories: 245, protein: 16, carbs: 18, fat: 12, fiber: 5,
    difficulty: 'easy',
    tags: ['plant-based', 'vegan', 'balanced'],
    imageEmoji: '🥦', grade: 'B',
    ingredients: [
      '300g firm tofu, pressed and cubed',
      '1 cup broccoli florets',
      '1 capsicum, sliced',
      '1 cup mushrooms',
      '2 tbsp oyster sauce, 1 tbsp soy sauce',
      '1 tsp cornflour',
    ],
    steps: [
      'Pan-fry tofu until golden on all sides; set aside.',
      'Stir-fry broccoli and capsicum on high heat 2 minutes.',
      'Add mushrooms; cook 2 more minutes.',
      'Return tofu; add sauces and 2 tbsp water.',
      'Add cornflour slurry to thicken; serve over rice.',
    ],
    tip: 'Press tofu between paper towels for 20 minutes — removes water for better crispiness.',
  },
  {
    id: 'sundubu-jjigae',
    name: 'Sundubu Jjigae (Soft Tofu Stew)',
    cuisine: 'Korean',
    prepTime: 5, cookTime: 15, servings: 1,
    calories: 225, protein: 18, carbs: 12, fat: 10, fiber: 3,
    difficulty: 'easy',
    tags: ['warming', 'high-protein', 'spicy'],
    imageEmoji: '🫕', grade: 'B',
    ingredients: [
      '1 tube (300g) silken tofu',
      '100g lean pork or seafood',
      '2 cups anchovy or veg broth',
      '2 tsp gochugaru (Korean chili flakes)',
      '1 egg, 1 tsp sesame oil',
      'Mushrooms, zucchini, spring onion',
    ],
    steps: [
      'Sauté garlic and gochugaru in sesame oil, 1 minute.',
      'Add protein; cook until seared.',
      'Pour in broth; bring to boil.',
      'Break tofu in large pieces; add vegetables.',
      'Crack egg on top; let set while simmering.',
      'Serve in the pot.',
    ],
    tip: 'The egg boosts protein significantly — don\'t skip it.',
  },
  {
    id: 'chawanmushi',
    name: 'Chawanmushi (Steamed Egg Custard)',
    cuisine: 'Japanese',
    prepTime: 10, cookTime: 15, servings: 2,
    calories: 130, protein: 11, carbs: 5, fat: 7, fiber: 0,
    difficulty: 'medium',
    tags: ['low-calorie', 'high-protein', 'silky'],
    imageEmoji: '🥚', grade: 'A',
    ingredients: [
      '3 large eggs',
      '350ml dashi or light broth',
      '1 tbsp light soy sauce, 1 tbsp mirin',
      'Toppings: prawn, shiitake, kamaboko',
    ],
    steps: [
      'Beat eggs gently — avoid bubbles.',
      'Stir in dashi, soy sauce, mirin.',
      'Strain through fine sieve; pour into cups over toppings.',
      'Steam on very low heat 12–15 minutes until just set.',
      'Serve immediately, topped with mitsuba or spring onion.',
    ],
    tip: 'Low and slow is key — high heat causes unsightly bubbles in the custard.',
  },
  {
    id: 'wonton-soup',
    name: 'Wonton Noodle Soup',
    cuisine: 'Cantonese',
    prepTime: 5, cookTime: 10, servings: 1,
    calories: 350, protein: 20, carbs: 48, fat: 7, fiber: 2,
    difficulty: 'easy',
    tags: ['soup', 'low-fat', 'comforting'],
    imageEmoji: '🥟', grade: 'B',
    ingredients: [
      '6–8 pork & prawn wontons',
      '80g thin egg noodles',
      '500ml clear pork or chicken broth',
      'Choy sum or bok choy',
      'White pepper, ½ tsp sesame oil',
    ],
    steps: [
      'Cook wontons in boiling water until they float, ~3 min.',
      'Cook noodles separately; drain.',
      'Heat broth; blanch vegetables.',
      'Assemble in bowl; pour hot broth over.',
      'Season with pepper and sesame oil.',
    ],
    tip: 'Ask for half the noodle portion and extra wontons — better protein-to-carb ratio.',
  },
  {
    id: 'buddha-bowl',
    name: 'Asian Buddha Bowl',
    cuisine: 'Fusion',
    prepTime: 15, cookTime: 20, servings: 1,
    calories: 520, protein: 24, carbs: 60, fat: 18, fiber: 9,
    difficulty: 'medium',
    tags: ['balanced', 'plant-forward', 'meal-prep'],
    imageEmoji: '🥗', grade: 'A',
    ingredients: [
      '100g brown rice, cooked',
      '100g edamame',
      '½ avocado, sliced',
      '1 carrot, shredded',
      '1 cup purple cabbage, shredded',
      '2 tbsp tahini, lemon juice, garlic (dressing)',
    ],
    steps: [
      'Cook brown rice per package.',
      'Arrange rice in bowl base.',
      'Add edamame, avocado, carrot, cabbage in sections.',
      'Whisk tahini with lemon, garlic, salt, and water until pourable.',
      'Drizzle dressing; sprinkle sesame seeds.',
    ],
    tip: 'Meal-prep the components for 4 days and assemble fresh — each bowl is different.',
  },
  {
    id: 'hainanese-chicken-rice',
    name: 'Hainanese Chicken Rice (Lighter)',
    cuisine: 'Singaporean',
    prepTime: 10, cookTime: 25, servings: 1,
    calories: 480, protein: 32, carbs: 52, fat: 12, fiber: 2,
    difficulty: 'medium',
    tags: ['protein-rich', 'classic'],
    imageEmoji: '🍗', grade: 'B',
    ingredients: [
      '150g chicken breast (poached)',
      '150g jasmine rice (cooked in broth)',
      '½ cucumber, sliced',
      '1 tbsp chili sauce, ginger paste',
      '½ tsp dark soy sauce',
    ],
    steps: [
      'Poach chicken breast in broth with ginger 20 minutes.',
      'Use the flavored broth to cook rice.',
      'Slice chicken thinly when cooled.',
      'Serve with cucumber and dipping sauces on side.',
    ],
    tip: 'Breast over thigh saves ~80 kcal. Ask for extra cucumber — it\'s virtually zero calories.',
  },
  {
    id: 'cold-soba',
    name: 'Zaru Soba (Cold Buckwheat Noodles)',
    cuisine: 'Japanese',
    prepTime: 5, cookTime: 5, servings: 1,
    calories: 290, protein: 13, carbs: 55, fat: 2, fiber: 4,
    difficulty: 'easy',
    tags: ['low-fat', 'quick', 'low-gi'],
    imageEmoji: '🍝', grade: 'A',
    ingredients: [
      '100g 100% buckwheat soba noodles',
      '150ml mentsuyu (diluted 1:3 with water)',
      'Wasabi, spring onion, nori strips',
    ],
    steps: [
      'Cook soba in boiling water 4–5 minutes.',
      'Rinse immediately under cold water; drain.',
      'Arrange on bamboo tray or plate.',
      'Prepare dipping sauce with wasabi and spring onion.',
      'Dip noodles — don\'t pour sauce over.',
    ],
    tip: '100% buckwheat soba has a lower GI than wheat noodles. Check labels — many brands mix wheat in.',
  },
  {
    id: 'mapo-tofu-light',
    name: 'Lighter Mapo Tofu',
    cuisine: 'Sichuan',
    prepTime: 5, cookTime: 12, servings: 2,
    calories: 240, protein: 18, carbs: 10, fat: 14, fiber: 2,
    difficulty: 'easy',
    tags: ['spicy', 'high-protein', 'plant-protein'],
    imageEmoji: '🌶️', grade: 'B',
    ingredients: [
      '400g silken tofu',
      '100g lean pork mince (or plant-based)',
      '2 tsp doubanjiang (chili bean paste)',
      '1 tsp Sichuan peppercorn, ground',
      '2 cloves garlic, 1 cup broth',
      '1 tsp cornflour',
    ],
    steps: [
      'Sauté garlic and doubanjiang in oil 1 minute until fragrant.',
      'Add pork; cook until browned.',
      'Pour in broth; bring to simmer.',
      'Gently add tofu cubes; simmer 5 minutes.',
      'Thicken with cornflour slurry; finish with Sichuan pepper.',
    ],
    tip: 'Silken tofu absorbs flavors better and has less fat than firm tofu in this dish.',
  },
  {
    id: 'chia-oat-bowl',
    name: 'Asian Chia & Oat Bowl',
    cuisine: 'Fusion',
    prepTime: 5, cookTime: 0, servings: 1,
    calories: 310, protein: 14, carbs: 42, fat: 9, fiber: 10,
    difficulty: 'easy',
    tags: ['breakfast', 'high-fiber', 'meal-prep'],
    imageEmoji: '🥣', grade: 'A',
    ingredients: [
      '50g rolled oats',
      '2 tbsp chia seeds',
      '180ml soy milk or low-fat milk',
      '1 tbsp honey',
      'Banana, berries, and almonds to top',
    ],
    steps: [
      'Mix oats, chia seeds, milk, and honey in a jar.',
      'Refrigerate overnight (minimum 4 hours).',
      'In the morning, top with banana, berries, and almonds.',
      'Eat cold or microwave 1 minute.',
    ],
    tip: 'Chia seeds expand 10× their volume, making this surprisingly filling despite low calories.',
  },
];

const GRADE_SCORE: Record<NutriGrade, number> = { A: 3, B: 2, C: 1, D: 0, E: 0 };

export function suggestRecipes(remainingCalories: number, goal?: GoalType): Recipe[] {
  if (remainingCalories < 50) return [];
  const candidates = RECIPES.filter(r => r.calories <= remainingCalories);
  const scored = candidates.map(r => {
    let score = GRADE_SCORE[r.grade];
    if (goal === 'lose') score += r.protein >= 20 ? 2 : 0;
    if (goal === 'gain') score += r.calories >= 350 ? 1 : 0;
    if (r.fat > 20) score -= 1;
    return { recipe: r, score };
  });
  return scored.sort((a, b) => b.score - a.score).slice(0, 3).map(s => s.recipe);
}
